### ISSUE TITLE
UC01b-F: User wants to create a new circle

### ISSUE THREAD

**Issue by anisfeld** [umbrela-savings/app#18]
> Now the user starts a circle. 

Warning: Several of the steps here are tricky and will require research.

- [x] start new circle button (on user page)
- [ ] ~Add payment method for 'instigator' (See #17)~ Deferred
- [x] new circle form 
  - [x] invite friends 
    - [x] emails / messages link to friends  (See #19)
      - [x] link points new user to sign up page 
  - [x] set circle contract (We want a flexible way to choose defaults -- likely through backend!)
- [x] User agrees to legal (Use placeholder contract for now, we'll assign this to lawyers)

**Comment by HaroldLeo** [comment]
Current progress:
- show a list of buttons linking towards each individual circle page
- can have people create a new group and the share button is implemented

To-do: 
- [ ] need an automatic update to the current circle list
- [ ] the backend doesn't seem to recognize the rules and the date variable from frontend, need more investigation
- [ ] the content of the sharing button useless right now, probably need backend integration for new user registration from the link
- [ ] need to find the search function for existing users so that they can access the new circle.

**Comment by anisfeld** [comment]
@HaroldLeo 
- [x] Capture "message" with list of invitees. POST to `/messages/` see API for what information to include. 
- [x] Then add that message to the team dashboard. The message will be on the dashboard until the circle starts.

**Comment by HaroldLeo** [comment]
1. Change the lists in MyCircleScreen to getting each info from each circle. 
2. Add a dashboard to show the joined members and message (until the circle starts).
3. Add the join circle button in MyCircleScreen, which means that having a check if the user is in the circle or not.

**Comment by HaroldLeo** [comment]
finished all and pushed to the dev branch.
